// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "afc0129f-5585-440d-8285-cdd28943a1e9";

const char SSID[]               = " your Network SSID (name)"; 
const char PASS[]               = "Network password ";    // (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "Secret device password";    // Secret device password

void onLed1Change();
void onLed2Change();
void onLed3Change();
void onLed4Change();
void onLed5Change();

bool led1;
bool led2;
bool led3;
bool led4;
bool led5;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(led1, READWRITE, ON_CHANGE, onLed1Change);
  ArduinoCloud.addProperty(led2, READWRITE, ON_CHANGE, onLed2Change);
  ArduinoCloud.addProperty(led3, READWRITE, ON_CHANGE, onLed3Change);
  ArduinoCloud.addProperty(led4, READWRITE, ON_CHANGE, onLed4Change);
  ArduinoCloud.addProperty(led5, READWRITE, ON_CHANGE, onLed5Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
